### ISSUE TITLE
change default port from 90 to 8090 or anything after 1024

### ISSUE THREAD

**Issue by hboutemy** [ltearno/pom-explorer#10]
on Unix, ports below 1024 are privilegied
I don't want to run pom-explorer as root...

**Comment by ltearno** [comment]
done, the default port is now 8090. Merci !

**Comment by hboutemy** [comment]
no associated commit? did you forget to push?

**Comment by ltearno** [comment]
Latest commit on the dev branch, pushed from devoxx an hour ago. As you
said i didn't associate to the issue ;)

Le jeu. 21 avr. 2016 14:38, Hervé Boutemy <notifications@github.com> a
écrit :

**Comment by ltearno** [comment]
Hervé, I ran this software on Linux and a lot of things were broken on the
dev branch. They are now fixed, so you should not get a blank page anymore.

By the way i don't have your personnal email, mine is ltearno@gmail.com
