### ISSUE TITLE
analyze dir .. fail

### ISSUE THREAD

**Issue by EXPEaneparaczki** [ltearno/pom-explorer#13]
Fresh install, just mvn installed, first run, trying to "analyze directory", and getting this error. From the string "settings file is not readable: C:\pgih\maven\3.2.1\conf\settings.xml" I assume something got hard coded in because I never had c:\pgih\maven on my computer ever.

** java.lang.IllegalArgumentException: settings file is not readable: C:\pgih\maven\3.2.1\conf\settings.xml **
org.jboss.shrinkwrap.resolver.impl.maven.util.Validate.readable(Validate.java:160)
org.jboss.shrinkwrap.resolver.impl.maven.ConfigurableMavenResolverSystemBaseImpl.configureFromFile(ConfigurableMavenResolverSystemBaseImpl.java:67)
org.jboss.shrinkwrap.resolver.impl.maven.ConfigurableMavenResolverSystemBaseImpl.configureFromFile(ConfigurableMavenResolverSystemBaseImpl.java:81)
org.jboss.shrinkwrap.resolver.impl.maven.ConfigurableMavenResolverSystemBaseImpl.fromFile(ConfigurableMavenResolverSystemBaseImpl.java:144)
org.jboss.shrinkwrap.resolver.impl.maven.ConfigurableMavenResolverSystemBaseImpl.fromFile(ConfigurableMavenResolverSystemBaseImpl.java:41)
fr.lteconsulting.pomexplorer.MavenResolver.init(MavenResolver.java:38)
fr.lteconsulting.pomexplorer.WorkingSession.mavenResolver(WorkingSession.java:66)
fr.lteconsulting.pomexplorer.PomAnalyzer.analyze(PomAnalyzer.java:69)
fr.lteconsulting.pomexplorer.commands.AnalyzeCommand.directory(AnalyzeCommand.java:16)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
java.lang.reflect.Method.invoke(Unknown Source)
fr.lteconsulting.pomexplorer.commands.Commands.takeCommand(Commands.java:210)

**Comment by ltearno** [comment]
Sorry it was not hard coded in the code but... in the default configuration file !

The latest commit solves this problem.

If you want to continue with the default settings, just remove or comment (#) the line beginning with

	session mavenSettingsFilePath C:\pgih\maven...

You can also use

	session mavenSettingsFilePath MAVEN_CONF_PATH

to specify the path to your maven settings file if pom explorer does not manage to find the system default.
