### ISSUE TITLE
${project.parent.version} not recognized

### ISSUE THREAD

**Issue by EXPEaneparaczki** [ltearno/pom-explorer#15]
Reproduce:
- have a project with a pom that has a parent and a dependency which's version is: `<version>${project.parent.version}</version>`
- run an analyze directory on the project's root folder, and see the error messages

${project.parent.version} is an implicit variable known by maven but unrecognized by this tool.

ie. with given parent:

`<parent>`
`<groupId>com.mycompany.www</groupId>`
`<artifactId>my-wonderful-parent</artifactId>`
`<version>0.1.25</version>`
`</parent>`

the bom.version property defined here:

`<properties>`
`<bom.version>${project.parent.version}</bom.version>`
`<.....`

should be 0.1.25

**Comment by ltearno** [comment]
Unfortunately i am not able to reproduce this error, both on master and dev branches...

I made up a project with a parent and a dependency to another project with version declared `${project.parent.version}`. When i run the `analyse directory` command i get no error and running `project details` shows the correct information, as you can see on the following screenshot :

![image](https://cloud.githubusercontent.com/assets/191069/17393972/f7e60e32-5a26-11e6-9d56-572a56e2c163.png)

The interesting line says :

	fr.lteconsulting:hexa-css:1.4:compile declared: fr.lteconsulting:hexa-css:${project.parent.version}

Are you sure you work on the tip of the branch ? master is `c33cd593cf676325a91d33c14202872c132ced62` and dev is on `b53601d76ddb4329d1ecb0a52f833df84e68b30c`.

If you could send me a small repro case, i will investigate more.

**Comment by EXPEaneparaczki** [comment]
Uh, the problem is way more complicated than I thought, will take a closer look when I get a chance.

**Comment by ltearno** [comment]
OK let me know... If you have just a small repro (just the pom.xml are
enough) it would be perfect !

Le jeu. 4 août 2016 à 10:44, EXPEaneparaczki <notifications@github.com> a
écrit :

**Comment by ltearno** [comment]
Hi, do you have a repro for this bug ? Thanks
