### ISSUE TITLE
Blank page on Linux

### ISSUE THREAD

**Issue by io7m** [ltearno/pom-explorer#16]
Hello.

I'm attempting to run the `pom-explorer.jar` compiled from commit a64f34f357a5bf36b6eb0cff3091003a87da7f36 and am getting a blank page on Linux.

```
$ java -jar pom-explorer/target/pom-explorer.jar &

Welcome to POM Explorer (beta) !
================================
visit http://localhost:8090 with a browser to access the application.


Aug 02, 2016 3:55:37 PM org.xnio.Xnio <clinit>
INFO: XNIO version 3.3.1.Final
Aug 02, 2016 3:55:37 PM org.xnio.nio.NioXnio <clinit>
INFO: XNIO NIO Implementation Version 3.3.1.Final

$ curl http://localhost:8090
$

$ curl -I http://localhost:8090
HTTP/1.1 404 Not Found
Connection: keep-alive
Content-Length: 0
Date: Tue, 02 Aug 2016 15:54:11 GMT

```

I get no error messages or anything else. Am I doing something wrong?

**Comment by io7m** [comment]
Some investigation has shown that the `pomexplorer-ui` directory is not being included in the produced jar. Moving the directory to `pom-explorer/src/main/resources/pomexplorer-ui` includes it correctly, but it also includes a lot of other files that you probably don't want in there.

**Comment by ltearno** [comment]
Thanks for your investigation i will have a look at it too, probably this
week.

**Comment by ltearno** [comment]
OK it is fixed with the 9047166 commit...
Thanks !

**Comment by RastaChaum** [comment]
Hello,

i've a similar issue on windows. I've a blank page when i launched http://localhost:8090 (IE, Chrome or Firefox done the same thing)
But it's not a 404. A page is launched, but it's blank. 

See code source of the page :


`<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8" />
    <title>Pom Explorer - beta !</title>

    <link rel="stylesheet" href="./material.min.css">
    <script src="./material.min.js"></script>
    <link rel="stylesheet" href="iconMaterialIcon.css">

    <link rel="stylesheet" href="app.css" type="text/css"/>

    
	<script src="tardigrade-bundle.js"></script>

    <script src="rx.all.min.js"></script>
    <script src="mustache.min.js"></script>

    <script src="app-bundle.js"></script>
</head>
<body>
</body>
</html>`


Here a snapshot of the Chrome's debug console with 2 javascript errors. Is it the problem ?

![capture](https://cloud.githubusercontent.com/assets/20987252/17617612/61d0f8a2-607b-11e6-981a-91f184de9fb0.PNG)

**Comment by RastaChaum** [comment]
I'm downloading the last version of firefox (portable) and it seems to run !
On my PC, it's the version 43.0. The lastest version of firefox is 48.0. 

Good to know.
