### ISSUE TITLE
Analyze command errors out

### ISSUE THREAD

**Issue by vaibhavguptaIITD** [ltearno/pom-explorer#2]
Hi,

Thanks for this great utility. I was refering to the article [here](https://dzone.com/articles/progress-626-managing-673) and wanted to try it out for my project. However, the analyze command errors out with the following message:

Error when interpreting a command !

    3 arguments of type :
    class fr.lteconsulting.pomexplorer.Client
    class fr.lteconsulting.pomexplorer.WorkingSession
    class java.lang.String
    null

Is there a way to see debug logs?

**Comment by ltearno** [comment]
Hi,

I've just improved the exception logging so with a `git pull && mvn install` you should get a better message. This will allow me to fix the problem, thanks a lot to give me the new error message !

Thanks

**Comment by vaibhavguptaIITD** [comment]
Thank you for the update. It looks parent pom of one of my project was pointing to wrong location. The project didn’t fall in the normal build cycle. This plugin has helped me to figure that out. Great!!
-- 
Vaibhav Gupta

On 10 July 2015 at 1:24:47 am, Arnaud Tournier (notifications@github.com) wrote:

Hi,

I've just improved the exception logging so with a git pull && mvn install you should get a better message. This will allow me to fix the problem, thanks a lot to give me the new error message !

Thanks

**Comment by ltearno** [comment]
OK Thanks !

Could you please kindly send me the stack trace, so i can add a clean
message instead of going to a null pointer exception ?

Anyway, glad that pom-explorer helped you !

Thanks
