### ISSUE TITLE
fr.lteconsulting.pomexplorer.change.project.SetPropertyCaller not under Git

### ISSUE THREAD

**Issue by RastaChaum** [ltearno/pom-explorer#20]
Checkout source from the DEV branch. But this class (fr.lteconsulting.pomexplorer.change.project.SetPropertyCaller) is missing.

**Comment by ltearno** [comment]
You should first verify that the project builds with Maven, i think it is
the case.

Then : the `SetPropertyCaller` class is generated at compile time by a java
code generator included with Pom Explorer. If you work with Eclipse and
it's your first time with a project using java code generation, you should
ensure :

- that you have the m2e-apt connector installed (if not, you simply go to
'Window > Eclipse marketplace...', search for 'm2e-apt' and go for
installation),
- that the java annotation processing is enabled (`Window > Preferences...
> Maven > Annotation Processing` then choose either the Automatic or the
experimental mode)
- refresh the project (ALT + F5)

It should now work...

Le mar. 23 août 2016 à 14:32, RastaChaum <notifications@github.com> a
écrit :

**Comment by RastaChaum** [comment]
Nice ! I've seen it for the Autothread classes, but i went near the problem for this class :\
So, all is right. I just had to add the autothread jar again in eclipse project preference.

I'm closing the issue.
