### ISSUE TITLE
POMs using private repositories seems not working

### ISSUE THREAD

**Issue by ajuluri** [ltearno/pom-explorer#23]
I'm trying to derive a dependency graph using this utility. Our Maven uses private repository... When I hit command _analyze directory C:\path_to_project_, I get the following exception in the stdout

Sep 15, 2016 4:25:30 PM org.jboss.shrinkwrap.resolver.impl.maven.logging.LogTransferListenertransferFailed
WARNING: Failed downloading com/deltadental/ets/ets/1.0/ets-1.0.pom from http://repo1.maven.org/maven2/. Reason:
org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact com.xyzcompany.ets:ets:pom:1.0 in central (http://repo1.maven.org/maven2)

**Comment by ltearno** [comment]
I think you should use the mavenSettings command to tell pom explorer where
you maven settings file is, and it should use the repositories declared in
it.

If your repositories are declared in your pom, it won't take it in
account(so it is an issue I agree). You could then temporarily put your
repositories in your setting file...

Thanks
