### ISSUE TITLE
IllegalArgumentException when analyzing project

### ISSUE THREAD

**Issue by smillies** [ltearno/pom-explorer#29]
When I analyze my project, I get 

java.lang.IllegalArgumentException: No enum constant fr.lteconsulting.pomexplorer.graph.relation.Scope.${TOMCAT.LIB.SCOPE}
java.lang.Enum.valueOf(Enum.java:238)
fr.lteconsulting.pomexplorer.graph.relation.Scope.valueOf(Scope.java:3)
fr.lteconsulting.pomexplorer.graph.relation.Scope.fromString(Scope.java:17)
fr.lteconsulting.pomexplorer.PomAnalysis.processProjectForCompleteness(PomAnalysis.java:338)
fr.lteconsulting.pomexplorer.PomAnalysis.loadAndCheckProject(PomAnalysis.java:377)
fr.lteconsulting.pomexplorer.PomAnalysis.processProjectForCompleteness(PomAnalysis.java:329)
fr.lteconsulting.pomexplorer.PomAnalysis.loadAndCheckProject(PomAnalysis.java:377)
fr.lteconsulting.pomexplorer.PomAnalysis.processProjectForCompleteness(PomAnalysis.java:329)
fr.lteconsulting.pomexplorer.PomAnalysis.completeLoadedProjects(PomAnalysis.java:223)
fr.lteconsulting.pomexplorer.PomAnalysis.runFullRecursiveAnalysis(PomAnalysis.java:68)
fr.lteconsulting.pomexplorer.commands.AnalyzeCommand.directory(AnalyzeCommand.java:29)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
fr.lteconsulting.pomexplorer.commands.Commands.takeCommand(Commands.java:251)
fr.lteconsulting.pomexplorer.AppFactory$1.onWebsocketMessage(AppFactory.java:169)
fr.lteconsulting.pomexplorer.webserver.WebServer$2$1.lambda$onFullTextMessage$0(WebServer.java:145)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)

**Comment by ltearno** [comment]
Oh I think I forgot to do variable interpolation in the <scope> nodes.

The error comes from the fact that Pom Explorer only accepts the official values for scope nodes. In some pom.xml your might have a dependency with a scope declared as `${TOMCAT.LIB.SCOPE}`.

I will try to publish a fix for that today, if possible. Maybe tomorrow since the issue should be easy to fix.

Thanks!

**Comment by ltearno** [comment]
I've fixed the issue on the master branch, could you please retry and confirm that the thing works?
Thanks a lot

**Comment by smillies** [comment]
Works now, thanks!
