### ISSUE TITLE
graph roots does not work with multiple root gavs

### ISSUE THREAD

**Issue by smillies** [ltearno/pom-explorer#30]
when I specify more than one gav for the graph roots command, I get an error message: verb 'roots' does not exist for command: graph

**Comment by ltearno** [comment]
Hi,
The functionnality now exists, thanks to you. And what is cool is that I added it at the level of the generic Gav filter, which means you can use it anytime a command accepts a gav filter.

The rule is this : you need to specify the gav filters by separating them by comma, but WITHOUT putting space in between. Here is an example : 

`graph roots org.spring,fr.lteconsulting` is correct

`graph roots org.spring, fr.lteconsulting` is incorrect

You can use this functionnality also in other commands, like `gav list` and so on...

Thanks, that was a good idea !
