### ISSUE TITLE
Feature request: exclude subdirectories

### ISSUE THREAD

**Issue by smillies** [ltearno/pom-explorer#31]
It would be great if one could specify an exclude list of subdirectories, either directly for the analyze command, or better yet for the session. This would be helpful in at least two situations:

1. Some of those subdirectories are irrelevant (e. g. not part of the build, or themselves only build-artefacts)
2. Some of those subdirectories have errors that prevent pom-explorer from analyzing them

I'd be willing to look at doing that myself, if you could give me an indication of where to start.
Otherwise, great tool, just what I needed!

**Comment by ltearno** [comment]
I think as you said you should store this information in the session class
(in the pomexplorer-core project) and use it in the PomAnalyzer class.
I don't have the sources in front of me so not 100% reliable, but should be
almost that.
Of course if you implement it, I am very happy!
Let me know if you have difficulties, I can help you then! If you don't
have enough time to implement, I can do it quickly I think.
Please do that on the dev branch so we don't break the application for
other users.
When it works, we will merge that in the master branch
Thanks again!

**Comment by smillies** [comment]
I have done something. With _session ignoreDirs_ you can now specify a comma-separated list of directories (no spaces in the list). You may use both simple names that are applied at each level of recursion, or absolute paths, e. g. 

> session ignoreDirs U:/project/Trunk/qm,distribution-set,integrationtests

My GitHub user (smillies) is not allowed to push to dev-branch ("remote: Permission to ltearno/pom-explorer.git denied to smillies.") I attach a zipped patch file for you to review.

[ignore_dirs.zip](https://github.com/ltearno/pom-explorer/files/720828/ignore_dirs.zip)

**Comment by ltearno** [comment]
Thanks a lot, and sorry for the long time !
I've integrated your commit and used your username and patch date.
