### ISSUE TITLE
Error when interpreting command garbage dependencies 

### ISSUE THREAD

**Issue by shadowwinds** [ltearno/pom-explorer#32]
Command class : GarbageCommand
Command method : dependencies
Argument : class: fr.lteconsulting.pomexplorer.ApplicationSession toString : fr.lteconsulting.pomexplorer.ApplicationSession@76f3b772
Argument : class: fr.lteconsulting.pomexplorer.AppFactory$2 toString : fr.lteconsulting.pomexplorer.AppFactory$2@d0326b8
Argument : class: fr.lteconsulting.pomexplorer.commands.CommandOptions toString : fr.lteconsulting.pomexplorer.commands.CommandOptions@2bff9652
Argument : class: fr.lteconsulting.pomexplorer.tools.FilteredGAVs toString : fr.lteconsulting.pomexplorer.tools.FilteredGAVs@78cd11fd
java.lang.ClassCastException: fr.lteconsulting.pomexplorer.model.Gav cannot be cast to java.lang.Comparable
java.util.Comparators$NaturalOrderComparator.compare(Comparators.java:47)
java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
java.util.TimSort.sort(TimSort.java:220)
java.util.Arrays.sort(Arrays.java:1512)
java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:348)
java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:423)
fr.lteconsulting.pomexplorer.commands.GarbageCommand.dependencies(GarbageCommand.java:153)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
fr.lteconsulting.pomexplorer.commands.Commands.takeCommand(Commands.java:251)
fr.lteconsulting.pomexplorer.AppFactory$1.onWebsocketMessage(AppFactory.java:169)
fr.lteconsulting.pomexplorer.webserver.WebServer$2$1.lambda$onFullTextMessage$0(WebServer.java:145)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)

**Comment by rivierej** [comment]
For info, I am facing the same issue with v1.2.

**Comment by ltearno** [comment]
Yes that's exactly the idea, reusing the Alphabetical Comparator !
I've fixed that in the latest commit. You can pull, rebuild and rerun.
Thanks and sorry for the inconvenience.

**Comment by ltearno** [comment]
Sorry @shadowwinds I didn't see the issue until today when @rivierej added a message.
Otherwise I would have fixed it earlier...

**Comment by rivierej** [comment]
Thanks for the quick fix and this great tool :)
