### ISSUE TITLE
Does pom-explorer require the transitive dependencies to be repositories in the same parent project directory?

### ISSUE THREAD

**Issue by juliangamble** [ltearno/pom-explorer#39]
Pom explorer advertises the ability to resolve transitive dependencies, and has a commit to address transitive dependencies. 

Does it actually read the pom.xml's of the child and grandchild projects? 

Or does it rely on being pointed to a parent project full of repositories - and grabbing the pom.xml of each?

What I'm getting at is whether if you point it at a parent repo, will it get the pom.xml of the child projects from the artifactory/maven jar archive/local rather than reading the other repo directory pom.xml files?

My question is: **Does pom-explorer require the transitive dependencies to be repositories in the same parent project directory?**

**Comment by ltearno** [comment]
Short answer is no, you can have pom files scattered everywhere.
By default it uses maven to fetch dependencies, and you can also provide
your own code for that.
I should write you a longer answer but have no time just right now. You can
have a look at the pom-explorer-core project inside the repo, there are
unit tests which will show you how to do that I believe.

Le sam. 25 nov. 2017 à 12:35, Julian Gamble <notifications@github.com> a
écrit :
