### ISSUE TITLE
where is pom-explorer-core published?

### ISSUE THREAD

**Issue by robstoll** [ltearno/pom-explorer#41]
do you publish your maven-artefact somewhere? I could not find it on maven central neither on jcenter.

**Comment by ltearno** [comment]
at the moment, it is not published, you have to build it yourself and store it on your local repository.
I will set up the publishing soon.
Thanks

**Comment by ltearno** [comment]
I have other project that i deploy on maven-central but not this one yet.
Will do soon

Le jeu. 18 janv. 2018 à 17:43, Robert Stoll <notifications@github.com> a
écrit :

**Comment by robstoll** [comment]
Since I need it now I have published it myself here:
https://bintray.com/robstoll/copies/pom-explorer

**Comment by ltearno** [comment]
Cool, i will let you know when available on Central...

Le ven. 26 janv. 2018 à 09:44, Robert Stoll <notifications@github.com> a
écrit :
