### ISSUE TITLE
Make server port configurable

### ISSUE THREAD

**Issue by criedel** [ltearno/pom-explorer#6]
You don’t always want to run this app as root. On many systems you must be root to bind services to ports lower than 1024 IIRC.

**Comment by ltearno** [comment]
I just implemented that on the "dev" branch.

Be careful that i am doing a major rewriting of pom explorer and on the dev branch, modifying pom graph has been unplugged. This functionnality will come back very soon...

So if you don't need to manipulate the pom graph, you can safely switch to the "dev" branch and use the command line to specify the listening tcp port.

Note that i added a comment about that in the readme...

I would be very interested by your feedbacks on pom explorer. What problem does it solve for you ? What could it solve but does not yet, general remarks and so on...

Thanks !
Arnaud

**Comment by criedel** [comment]
Well I just wanted to try it out. Didn’t work on my mac unfortunately. Loading projects that is.
I’ll try the dev branch tomorrow, let’s see if it can handle non-windows filesystems ;)
