### ISSUE TITLE
Compatibility with yEd

### ISSUE THREAD

**Issue by Olion23** [ltearno/pom-explorer#66]
I've seen it recommended to use yEd to visualize the exported GraphML file, but it doesn't seem to work right out of the box the way it's described. Nodes have no titles, and everything loads into yEd as a single column of nodes. I realize this is something to bring up with yEd, but if others are using it to visualize their POM Explorer graphs, maybe somebody else has dealt with this already.

**Comment by LeoUfimtsev** [comment]
I ran into this issue as well. You have to spend some time manually converting things after import.


Yed:
- select default node/edge (these will be used for opening graphml file:
	- sample square
	- directed arrow (with pointer)

- Now Open diagram
- Edit -> Properties Mapper
  Map Vertex Label to Label Text

- Layout 
  -> hierarchical, bottom to top.
- Tools -> Fit node to label.

ref:
https://github.com/ltearno/pom-explorer/issues/8
https://yed.yworks.com/support/manual/properties_mapper.html

**Comment by LeoUfimtsev** [comment]
![image](https://user-images.githubusercontent.com/4347147/45598823-de9c4a00-b9af-11e8-9865-9402c21476b6.png)
