### ISSUE TITLE
version could be properties which defined in project gav

### ISSUE THREAD

**Issue by cccfeng** [ltearno/pom-explorer#69]
https://github.com/ltearno/pom-explorer/blob/db4246ce7f149fec99cfdab63af3f42ee764cc76/pom-explorer-core/src/main/java/fr/lteconsulting/pomexplorer/Project.java#L96

parent --> 
      child1 (g - a -v)
      child2 (groupId - artifactId - ${xxx.version})

xxx.version is the property in parent artifactId

**Comment by robstoll** [comment]
Thanks for your input, I am not really sure if I get you right. Do you mean something as the following:
parent
```
<properties><xxx.version>1.0</xxx.version></properties>
```
child
```
<parent>...</parent>
<version>${xxx.version}</version>
```

**Comment by CCCube** [comment]
You got it. I found this scene in a real project.

**Comment by robstoll** [comment]
But  `project.getVersion()` is not `null` in such a case (it's `${xxx.version}`), so the problem that this is thrown exception must be elsewhere.

**Comment by robstoll** [comment]
It seems to me that an interpolation is required here so that the version resolves to what is defined in the parent (or wherever it was defined). Is that your actual problem?

**Comment by CCCube** [comment]
Yes. In fact the program try to compare version and "${parent.version}" , so it is the same that the version equals `${xxx.version}` or something else

**Comment by robstoll** [comment]
Ok, I think now we are getting to the point 😄 
You do not experience the exception in line 96 but in line 105 `Non resolved project's GAV: ...`
Would you like to try solve the problem yourself? I could give you some hints.

**Comment by CCCube** [comment]
Ok,I would like to try it. Is the logic right to solve this problem ?
when version is not null, add the code
1. whether the version resolved ? if not 
2. whether the version is a maven val, start with `${` and end with `}`
3. if version is a maven val , then try to get from self properties. 
4. when self properties is null , try to get from it's parent gav
5. or else throw the RuntimeException

**Comment by robstoll** [comment]
I think that's more or less it. The good thing though, there is already logic for this interpolateValue. I have created two regressiontests for you. They should be green at the end, I think you will have to adjust them (or the poms) a little bit so that the versions fit at the end. Have fun and if you have questions keep them posted here

**Comment by CCCube** [comment]
Got it. I will try to finish it.
