### ISSUE TITLE
Dependencies missing

### ISSUE THREAD

**Issue by nukeu666** [ltearno/pom-explorer#73]
When i try to build pom explorer, it gives the following error for missing dependencies

Failed to execute goal on project pom-explorer: Could not resolve dependencies for project fr.lteconsulting:pom-explorer:jar:1.4-SNAPSHOT: The following artifacts could not be resolved: fr.lteconsulting:pom-explorer-core:jar:1.4-SNAPSHOT, fr.lteconsulting:autothreaded:jar:1.4-SNAPSHOT: Could not find artifact fr.lteconsulting:pom-explorer-core:jar:1.4-SNAPSHOT -> [Help 1]

I checked maven repository and these packages don't exist for older version either

**Comment by robstoll** [comment]
Pom-explorer is a multi-module project where core and autothreaded are submodules. Or in other words they are built in the same run. What mvn command are you using?

**Comment by robstoll** [comment]
closing as I did not get an answer.
