### ISSUE TITLE
Cannot analyze directory

### ISSUE THREAD

**Issue by Oleg7722** [ltearno/pom-explorer#74]
After trying to analyze directory by command  analyze directory D:\zzz\zzz\zzz got error message "verb 'directory' does not exist for command: analyze" . Analyze does not work at at all, in any combination.
Could you please fix?

**Comment by robstoll** [comment]
does your path have withespaces? if so, try to wrap it into `"`

**Comment by Oleg7722** [comment]
Yes sir, I tried to enclose path, tried to run it without any path, tried to run it just with analyze command without directory command- in this case it reads that "verb 'main' does not exist for command: analyze".
Regards

**Comment by Oleg7722** [comment]
Sorry, it started to work. Closing question.
Regards!

**Comment by robstoll** [comment]
No worries
